// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: storage_service.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type InitializeArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitializeArgs) Reset() {
	*x = InitializeArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitializeArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeArgs) ProtoMessage() {}

func (x *InitializeArgs) ProtoReflect() protoreflect.Message {
	mi := &file_storage_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeArgs.ProtoReflect.Descriptor instead.
func (*InitializeArgs) Descriptor() ([]byte, []int) {
	return file_storage_service_proto_rawDescGZIP(), []int{0}
}

type InitializeResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorStatus   *ErrorStatus `protobuf:"bytes,1,opt,name=errorStatus,proto3" json:"errorStatus,omitempty"`
	AvailableSize int64        `protobuf:"varint,2,opt,name=availableSize,proto3" json:"availableSize,omitempty"`
}

func (x *InitializeResult) Reset() {
	*x = InitializeResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitializeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResult) ProtoMessage() {}

func (x *InitializeResult) ProtoReflect() protoreflect.Message {
	mi := &file_storage_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResult.ProtoReflect.Descriptor instead.
func (*InitializeResult) Descriptor() ([]byte, []int) {
	return file_storage_service_proto_rawDescGZIP(), []int{1}
}

func (x *InitializeResult) GetErrorStatus() *ErrorStatus {
	if x != nil {
		return x.ErrorStatus
	}
	return nil
}

func (x *InitializeResult) GetAvailableSize() int64 {
	if x != nil {
		return x.AvailableSize
	}
	return 0
}

type CreateFileArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *CreateFileArgs) Reset() {
	*x = CreateFileArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFileArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileArgs) ProtoMessage() {}

func (x *CreateFileArgs) ProtoReflect() protoreflect.Message {
	mi := &file_storage_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileArgs.ProtoReflect.Descriptor instead.
func (*CreateFileArgs) Descriptor() ([]byte, []int) {
	return file_storage_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFileArgs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type CreateFileResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorStatus *ErrorStatus `protobuf:"bytes,1,opt,name=errorStatus,proto3" json:"errorStatus,omitempty"`
}

func (x *CreateFileResult) Reset() {
	*x = CreateFileResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileResult) ProtoMessage() {}

func (x *CreateFileResult) ProtoReflect() protoreflect.Message {
	mi := &file_storage_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileResult.ProtoReflect.Descriptor instead.
func (*CreateFileResult) Descriptor() ([]byte, []int) {
	return file_storage_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFileResult) GetErrorStatus() *ErrorStatus {
	if x != nil {
		return x.ErrorStatus
	}
	return nil
}

type ReadFileArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path   string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset int64  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Count  int64  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ReadFileArgs) Reset() {
	*x = ReadFileArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadFileArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileArgs) ProtoMessage() {}

func (x *ReadFileArgs) ProtoReflect() protoreflect.Message {
	mi := &file_storage_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileArgs.ProtoReflect.Descriptor instead.
func (*ReadFileArgs) Descriptor() ([]byte, []int) {
	return file_storage_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReadFileArgs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadFileArgs) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadFileArgs) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ReadFileResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorStatus *ErrorStatus `protobuf:"bytes,1,opt,name=errorStatus,proto3" json:"errorStatus,omitempty"`
	Buffer      []byte       `protobuf:"bytes,2,opt,name=buffer,proto3" json:"buffer,omitempty"`
	Count       int32        `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ReadFileResult) Reset() {
	*x = ReadFileResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadFileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResult) ProtoMessage() {}

func (x *ReadFileResult) ProtoReflect() protoreflect.Message {
	mi := &file_storage_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResult.ProtoReflect.Descriptor instead.
func (*ReadFileResult) Descriptor() ([]byte, []int) {
	return file_storage_service_proto_rawDescGZIP(), []int{5}
}

func (x *ReadFileResult) GetErrorStatus() *ErrorStatus {
	if x != nil {
		return x.ErrorStatus
	}
	return nil
}

func (x *ReadFileResult) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

func (x *ReadFileResult) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type WriteFileArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path        string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset      int64  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Buffer      []byte `protobuf:"bytes,3,opt,name=buffer,proto3" json:"buffer,omitempty"`
	IsChainCall bool   `protobuf:"varint,4,opt,name=isChainCall,proto3" json:"isChainCall,omitempty"`
}

func (x *WriteFileArgs) Reset() {
	*x = WriteFileArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteFileArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileArgs) ProtoMessage() {}

func (x *WriteFileArgs) ProtoReflect() protoreflect.Message {
	mi := &file_storage_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileArgs.ProtoReflect.Descriptor instead.
func (*WriteFileArgs) Descriptor() ([]byte, []int) {
	return file_storage_service_proto_rawDescGZIP(), []int{6}
}

func (x *WriteFileArgs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileArgs) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WriteFileArgs) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

func (x *WriteFileArgs) GetIsChainCall() bool {
	if x != nil {
		return x.IsChainCall
	}
	return false
}

type WriteFileResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorStatus *ErrorStatus `protobuf:"bytes,1,opt,name=errorStatus,proto3" json:"errorStatus,omitempty"`
}

func (x *WriteFileResult) Reset() {
	*x = WriteFileResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteFileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResult) ProtoMessage() {}

func (x *WriteFileResult) ProtoReflect() protoreflect.Message {
	mi := &file_storage_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResult.ProtoReflect.Descriptor instead.
func (*WriteFileResult) Descriptor() ([]byte, []int) {
	return file_storage_service_proto_rawDescGZIP(), []int{7}
}

func (x *WriteFileResult) GetErrorStatus() *ErrorStatus {
	if x != nil {
		return x.ErrorStatus
	}
	return nil
}

type RemoveArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *RemoveArgs) Reset() {
	*x = RemoveArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveArgs) ProtoMessage() {}

func (x *RemoveArgs) ProtoReflect() protoreflect.Message {
	mi := &file_storage_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveArgs.ProtoReflect.Descriptor instead.
func (*RemoveArgs) Descriptor() ([]byte, []int) {
	return file_storage_service_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveArgs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RemoveResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorStatus *ErrorStatus `protobuf:"bytes,1,opt,name=errorStatus,proto3" json:"errorStatus,omitempty"`
}

func (x *RemoveResult) Reset() {
	*x = RemoveResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResult) ProtoMessage() {}

func (x *RemoveResult) ProtoReflect() protoreflect.Message {
	mi := &file_storage_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResult.ProtoReflect.Descriptor instead.
func (*RemoveResult) Descriptor() ([]byte, []int) {
	return file_storage_service_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveResult) GetErrorStatus() *ErrorStatus {
	if x != nil {
		return x.ErrorStatus
	}
	return nil
}

type GetFileInfoArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *GetFileInfoArgs) Reset() {
	*x = GetFileInfoArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileInfoArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoArgs) ProtoMessage() {}

func (x *GetFileInfoArgs) ProtoReflect() protoreflect.Message {
	mi := &file_storage_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoArgs.ProtoReflect.Descriptor instead.
func (*GetFileInfoArgs) Descriptor() ([]byte, []int) {
	return file_storage_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetFileInfoArgs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetFileInfoResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorStatus *ErrorStatus `protobuf:"bytes,1,opt,name=errorStatus,proto3" json:"errorStatus,omitempty"`
	FileSize    uint64       `protobuf:"varint,2,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
}

func (x *GetFileInfoResult) Reset() {
	*x = GetFileInfoResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileInfoResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoResult) ProtoMessage() {}

func (x *GetFileInfoResult) ProtoReflect() protoreflect.Message {
	mi := &file_storage_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoResult.ProtoReflect.Descriptor instead.
func (*GetFileInfoResult) Descriptor() ([]byte, []int) {
	return file_storage_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetFileInfoResult) GetErrorStatus() *ErrorStatus {
	if x != nil {
		return x.ErrorStatus
	}
	return nil
}

func (x *GetFileInfoResult) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type CopyArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	NewPath string `protobuf:"bytes,2,opt,name=newPath,proto3" json:"newPath,omitempty"`
}

func (x *CopyArgs) Reset() {
	*x = CopyArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyArgs) ProtoMessage() {}

func (x *CopyArgs) ProtoReflect() protoreflect.Message {
	mi := &file_storage_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyArgs.ProtoReflect.Descriptor instead.
func (*CopyArgs) Descriptor() ([]byte, []int) {
	return file_storage_service_proto_rawDescGZIP(), []int{12}
}

func (x *CopyArgs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CopyArgs) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

type CopyResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorStatus *ErrorStatus `protobuf:"bytes,1,opt,name=errorStatus,proto3" json:"errorStatus,omitempty"`
}

func (x *CopyResult) Reset() {
	*x = CopyResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyResult) ProtoMessage() {}

func (x *CopyResult) ProtoReflect() protoreflect.Message {
	mi := &file_storage_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyResult.ProtoReflect.Descriptor instead.
func (*CopyResult) Descriptor() ([]byte, []int) {
	return file_storage_service_proto_rawDescGZIP(), []int{13}
}

func (x *CopyResult) GetErrorStatus() *ErrorStatus {
	if x != nil {
		return x.ErrorStatus
	}
	return nil
}

type MoveArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	NewPath string `protobuf:"bytes,2,opt,name=newPath,proto3" json:"newPath,omitempty"`
}

func (x *MoveArgs) Reset() {
	*x = MoveArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveArgs) ProtoMessage() {}

func (x *MoveArgs) ProtoReflect() protoreflect.Message {
	mi := &file_storage_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveArgs.ProtoReflect.Descriptor instead.
func (*MoveArgs) Descriptor() ([]byte, []int) {
	return file_storage_service_proto_rawDescGZIP(), []int{14}
}

func (x *MoveArgs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MoveArgs) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

type MoveResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorStatus *ErrorStatus `protobuf:"bytes,1,opt,name=errorStatus,proto3" json:"errorStatus,omitempty"`
}

func (x *MoveResult) Reset() {
	*x = MoveResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResult) ProtoMessage() {}

func (x *MoveResult) ProtoReflect() protoreflect.Message {
	mi := &file_storage_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResult.ProtoReflect.Descriptor instead.
func (*MoveResult) Descriptor() ([]byte, []int) {
	return file_storage_service_proto_rawDescGZIP(), []int{15}
}

func (x *MoveResult) GetErrorStatus() *ErrorStatus {
	if x != nil {
		return x.ErrorStatus
	}
	return nil
}

var File_storage_service_proto protoreflect.FileDescriptor

var file_storage_service_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0c, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x10, 0x0a, 0x0e, 0x49, 0x6e, 0x69,
	0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x41, 0x72, 0x67, 0x73, 0x22, 0x6b, 0x0a, 0x10, 0x49,
	0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x31, 0x0a, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x24, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x41, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x45,
	0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x31, 0x0a, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x50, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6c,
	0x65, 0x41, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x71, 0x0a, 0x0e, 0x52, 0x65, 0x61, 0x64, 0x46,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x31, 0x0a, 0x0b, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x62, 0x75,
	0x66, 0x66, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x75, 0x0a, 0x0d, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x41, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x66, 0x66, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x12,
	0x20, 0x0a, 0x0b, 0x69, 0x73, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x43, 0x61, 0x6c, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x43, 0x61, 0x6c,
	0x6c, 0x22, 0x44, 0x0a, 0x0f, 0x57, 0x72, 0x69, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x31, 0x0a, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0b, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x20, 0x0a, 0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x41, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x41, 0x0a, 0x0c, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x31, 0x0a, 0x0b, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x25, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x41, 0x72, 0x67, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x22, 0x62, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x31, 0x0a, 0x0b, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0b,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x38, 0x0a, 0x08, 0x43, 0x6f, 0x70, 0x79, 0x41,
	0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x77, 0x50, 0x61,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x77, 0x50, 0x61, 0x74,
	0x68, 0x22, 0x3f, 0x0a, 0x0a, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x31, 0x0a, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x38, 0x0a, 0x08, 0x4d, 0x6f, 0x76, 0x65, 0x41, 0x72, 0x67, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x77, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x77, 0x50, 0x61, 0x74, 0x68, 0x22, 0x3f, 0x0a, 0x0a,
	0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x31, 0x0a, 0x0b, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xa3, 0x03,
	0x0a, 0x07, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x38, 0x0a, 0x0a, 0x49, 0x6e, 0x69,
	0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x69,
	0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x14, 0x2e, 0x70, 0x62,
	0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c,
	0x65, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c,
	0x65, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x32, 0x0a,
	0x08, 0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x12, 0x2e, 0x70, 0x62,
	0x2e, 0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x00, 0x12, 0x35, 0x0a, 0x09, 0x57, 0x72, 0x69, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x11,
	0x2e, 0x70, 0x62, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x41, 0x72, 0x67,
	0x73, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x12, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x72,
	0x67, 0x73, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69,
	0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x00, 0x12, 0x26, 0x0a, 0x04, 0x43, 0x6f, 0x70, 0x79, 0x12, 0x0c, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x6f, 0x70, 0x79, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x6f, 0x70, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x26, 0x0a, 0x04, 0x4d,
	0x6f, 0x76, 0x65, 0x12, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x41, 0x72, 0x67,
	0x73, 0x1a, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_storage_service_proto_rawDescOnce sync.Once
	file_storage_service_proto_rawDescData = file_storage_service_proto_rawDesc
)

func file_storage_service_proto_rawDescGZIP() []byte {
	file_storage_service_proto_rawDescOnce.Do(func() {
		file_storage_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_storage_service_proto_rawDescData)
	})
	return file_storage_service_proto_rawDescData
}

var file_storage_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_storage_service_proto_goTypes = []interface{}{
	(*InitializeArgs)(nil),    // 0: pb.InitializeArgs
	(*InitializeResult)(nil),  // 1: pb.InitializeResult
	(*CreateFileArgs)(nil),    // 2: pb.CreateFileArgs
	(*CreateFileResult)(nil),  // 3: pb.CreateFileResult
	(*ReadFileArgs)(nil),      // 4: pb.ReadFileArgs
	(*ReadFileResult)(nil),    // 5: pb.ReadFileResult
	(*WriteFileArgs)(nil),     // 6: pb.WriteFileArgs
	(*WriteFileResult)(nil),   // 7: pb.WriteFileResult
	(*RemoveArgs)(nil),        // 8: pb.RemoveArgs
	(*RemoveResult)(nil),      // 9: pb.RemoveResult
	(*GetFileInfoArgs)(nil),   // 10: pb.GetFileInfoArgs
	(*GetFileInfoResult)(nil), // 11: pb.GetFileInfoResult
	(*CopyArgs)(nil),          // 12: pb.CopyArgs
	(*CopyResult)(nil),        // 13: pb.CopyResult
	(*MoveArgs)(nil),          // 14: pb.MoveArgs
	(*MoveResult)(nil),        // 15: pb.MoveResult
	(*ErrorStatus)(nil),       // 16: pb.ErrorStatus
}
var file_storage_service_proto_depIdxs = []int32{
	16, // 0: pb.InitializeResult.errorStatus:type_name -> pb.ErrorStatus
	16, // 1: pb.CreateFileResult.errorStatus:type_name -> pb.ErrorStatus
	16, // 2: pb.ReadFileResult.errorStatus:type_name -> pb.ErrorStatus
	16, // 3: pb.WriteFileResult.errorStatus:type_name -> pb.ErrorStatus
	16, // 4: pb.RemoveResult.errorStatus:type_name -> pb.ErrorStatus
	16, // 5: pb.GetFileInfoResult.errorStatus:type_name -> pb.ErrorStatus
	16, // 6: pb.CopyResult.errorStatus:type_name -> pb.ErrorStatus
	16, // 7: pb.MoveResult.errorStatus:type_name -> pb.ErrorStatus
	0,  // 8: pb.Storage.Initialize:input_type -> pb.InitializeArgs
	2,  // 9: pb.Storage.CreateFile:input_type -> pb.CreateFileArgs
	4,  // 10: pb.Storage.ReadFile:input_type -> pb.ReadFileArgs
	6,  // 11: pb.Storage.WriteFile:input_type -> pb.WriteFileArgs
	8,  // 12: pb.Storage.Remove:input_type -> pb.RemoveArgs
	10, // 13: pb.Storage.GetFileInfo:input_type -> pb.GetFileInfoArgs
	12, // 14: pb.Storage.Copy:input_type -> pb.CopyArgs
	14, // 15: pb.Storage.Move:input_type -> pb.MoveArgs
	1,  // 16: pb.Storage.Initialize:output_type -> pb.InitializeResult
	3,  // 17: pb.Storage.CreateFile:output_type -> pb.CreateFileResult
	5,  // 18: pb.Storage.ReadFile:output_type -> pb.ReadFileResult
	7,  // 19: pb.Storage.WriteFile:output_type -> pb.WriteFileResult
	9,  // 20: pb.Storage.Remove:output_type -> pb.RemoveResult
	11, // 21: pb.Storage.GetFileInfo:output_type -> pb.GetFileInfoResult
	13, // 22: pb.Storage.Copy:output_type -> pb.CopyResult
	15, // 23: pb.Storage.Move:output_type -> pb.MoveResult
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_storage_service_proto_init() }
func file_storage_service_proto_init() {
	if File_storage_service_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_storage_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitializeArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitializeResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFileArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFileResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadFileArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadFileResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteFileArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteFileResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileInfoArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileInfoResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_storage_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_service_proto_goTypes,
		DependencyIndexes: file_storage_service_proto_depIdxs,
		MessageInfos:      file_storage_service_proto_msgTypes,
	}.Build()
	File_storage_service_proto = out.File
	file_storage_service_proto_rawDesc = nil
	file_storage_service_proto_goTypes = nil
	file_storage_service_proto_depIdxs = nil
}
